name: test
run-name: test application with storybook
on: [push]
jobs:
    unit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # required to get git history
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.16.0"
            - run: npm install yarn -g
            - run: cd web/ && yarn && yarn test-vite
    chromatic:
        needs: [unit]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # required to get git history
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.16.0"
            - run: npm install yarn -g
            - run: cd web/ && yarn
            - uses: chromaui/action@v1
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  workingDir: web/
